from pandas import DataFrame, read_csv

import matplotlib.pyplot as plt
import pandas as pd #this is how I usually import pandas
import sys #only needed to determine Python version number
import matplotlib #only needed to determine Matplotlib version number


print('Python version ' + sys.version)
print('Pandas version ' + pd.__version__)
print('Matplotlib version ' + matplotlib.__version__)


COL_NAMES = [
    "Date",
    "Game Number",
    "Day of Week",
    "Visiting Team",
    "Visiting Team League",
    "Visiting Team Game Number",
    "Home Team",
    "Home Team League",
    "Home Team Game Number",
    "Visiting Score",
    "Home Score",
    "Game Length",
    "Time of Day",
    "Completion Information",
    "Forfeit Information",
    "Protest Information",
    "Park ID",
    "Attendance",
    "Time of Game",
    "Visiting Line Score",
    "Home Line Score",
    "V At-Bats",
    "V Hits",
    "V Doubles",
    "V Triples",
    "V Homeruns",
    "V RBIs",
    "V Sacrifice Hits",
    "V Sacrifice Flies",
    "V Hit-By-Pitch",
    "V Walks",
    "V Intentional Walks",
    "V Strikeouts",
    "V Stolen Bases",
    "V Caught Stealing",
    "V Double Plays",
    "V Catcher Interference",
    "V Left On Base",
    "V Pitchers Used",
    "V Individual Earned Runs",
    "V Team Earned Runs",
    "V Wild Pitches",
    "V Balks",
    "V Wild Pitches",
    "V Putouts",
    "V Assists",
    "V Errors",
    "V Passed Balls",
    "V Double Plays",
    "V Triple Plays",
    "V Double Plays",
    "H At-Bats",
    "H Hits",
    "H Doubles",
    "H Triples",
    "H Homeruns",
    "H RBIs",
    "H Sacrifice Hits",
    "H Sacrifice Flies",
    "H Hit-By-Pitch",
    "H Walks",
    "H Intentional Walks",
    "H Strikeouts",
    "H Stolen Bases",
    "H Caught Stealing",
    "H Double Plays",
    "H Catcher Interference",
    "H Left On Base",
    "H Pitchers Used",
    "H Individual Earned Runs",
    "H Team Earned Runs",
    "H Wild Pitches",
    "H Balks",
    "H Wild Pitches",
    "H Putouts",
    "H Assists",
    "H Errors",
    "H Passed Balls",
    "H Double Plays",
    "H Triple Plays",
    "H Double Plays",
    "Home Umpire ID",
    "Home Umpire Name",
    "1b Umpire ID",
    "1b Umpire Name",
    "2b Umpire ID",
    "2b Umpire Name",
    "3b Umpire ID",
    "3b Umpire Name",
    "LF Umpire ID",
    "LF Umpire Name",
    "RF Umpire ID",
    "RF Umpire Name",
    "Visiting Manager ID",
    "Visiting Manager Name",
    "Home Manager ID",
    "Home Manager Name",
    "Winning Pitcher ID",
    "Winning Pitcher Name",
    "Losing Pitcher ID",
    "Losing Pitcher Name",
    "Saving Pitcher ID",
    "Saving Pitcher Name",
    "Game Winning RBI Batter ID",
    "Game Winning RBI Batter Name",
    "Visiting Starting Pitcher ID",
    "Visiting Starting Pitcher Name",
    "Home Starting Pitcher ID",
    "Home Starting Pitcher Name",
    "V Player 1 ID",
    "V Player 2 ID",
    "V Player 3 ID",
    "V Player 4 ID",
    "V Player 5 ID",
    "V Player 6 ID",
    "V Player 7 ID",
    "V Player 8 ID",
    "V Player 9 ID",
    "V Player 1 Name",
    "V Player 2 Name",
    "V Player 3 Name",
    "V Player 4 Name",
    "V Player 5 Name",
    "V Player 6 Name",
    "V Player 7 Name",
    "V Player 8 Name",
    "V Player 9 Name",
    "V Player 1 Defensive Position",
    "V Player 2 Defensive Position",
    "V Player 3 Defensive Position",
    "V Player 4 Defensive Position",
    "V Player 5 Defensive Position",
    "V Player 6 Defensive Position",
    "V Player 7 Defensive Position",
    "V Player 8 Defensive Position",
    "V Player 9 Defensive Position",
    "H Position Player 1 ID",
    "H Position Player 2 ID",
    "H Position Player 3 ID",
    "H Position Player 4 ID",
    "H Position Player 5 ID",
    "H Position Player 6 ID",
    "H Position Player 7 ID",
    "H Position Player 8 ID",
    "H Position Player 9 ID",
    "H Position Player 1 Name",
    "H Position Player 2 Name",
    "H Position Player 3 Name",
    "H Position Player 4 Name",
    "H Position Player 5 Name",
    "H Position Player 6 Name",
    "H Position Player 7 Name",
    "H Position Player 8 Name",
    "H Position Player 9 Name",
    "H Position Player 1 Defensive Position",
    "H Position Player 2 Defensive Position",
    "H Position Player 3 Defensive Position",
    "H Position Player 4 Defensive Position",
    "H Position Player 5 Defensive Position",
    "H Position Player 6 Defensive Position",
    "H Position Player 7 Defensive Position",
    "H Position Player 8 Defensive Position",
    "H Position Player 9 Defensive Position",
    "Additional Information",
    "Acquisition Information"
]

df = pd.read_csv(filepath_or_buffer="data/GL2010.txt", header=None,
                 names=COL_NAMES)

print("SIZE: " + str(df.size) + " COLUMNS: " + str(df.columns) + "\n")

#print("Visiting teams!: \n" + str(df[3].unique()) + "\n")


#df.plot(x="V Homeruns", y="H Homeruns", kind="scatter")

pl = pd.DataFrame(names=['Player', 'wins', 'losses'])




matplotlib.pyplot.show()
